### ISSUE TITLE
vscode integration

### ISSUE THREAD

**Issue by kjeremy** [build-server-protocol/build-server-protocol#120]
This looks interesting. I see vscode mentioned on the website but do not see any client code anywhere. Is there a client-side implementation of the BSP such that if someone where to implement the server for their language/tool things could "just work" similar to writing an LSP server?

**Comment by jastice** [comment]
Yes, BSP clients are implemented in the [Scala plugin for IntelliJ IDEA](https://github.com/JetBrains/intellij-scala) and [Metals](https://github.com/scalameta/metals).

**Comment by kjeremy** [comment]
It looks like those are scala specific. If I implemented a BSP server for a separate language like rust would I have to write a full blown client side implementation as well? vscode ultimately uses the `client` in [vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node/) to communicate with LSP servers and I am looking for something similar.

**Comment by jastice** [comment]
At the moment we only have Scala-focused clients, yes. We want to bring the BSP support to the IntelliJ platform, however, which would enable integration with servers in other languages as well, including ployglot servers. If you are interested in writing a server implementation I'd be happy to collaborate to get it working from the client side.

**Comment by olafurpg** [comment]
@kjeremy BSP is currently mostly used where language servers are the build clients. The biggest value in BSP is that a language server can support multiple build tools using the same API. In some language ecosystems there is only one widely used build system (for example cargo for rust) so there is less value in supporting BSP. In the JVM ecosystem the situation is different since there are many build tools.

**Comment by olafurpg** [comment]
I estimate it wouldn’t be too hard to implement a BSP client integration for VS Code. I’m not sure it would be so useful on its own however. The biggest use cases where BSP has been helpful so far is where a language server can query the build tool for external library dependencies, source directories and compiler options in order to power features like completions and code navigation. End users don’t interact with BSP much directly.
